config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#show"

  resources :users do
    resources :exams
    resources :videos
    resources :mcqs
    resources :ebooks
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ebook.rb
class Ebook < ApplicationRecord
  belongs_to :user
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user
end

app/models/mcq.rb
class Mcq < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
    devise :omniauthable, omniauth_providers: %i[facebook]
    attr_accessor :terms_accepted, :image
    mount_uploader :image, ImageUploader
    def self.from_omniauth(auth)
      name_split = auth.info.name.split(" ")
      user = User.where(email: auth.info.email).first
      user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
        user
    end

    has_many :exams
    has_many :mcqs
    has_many :videos
    has_many :ebooks
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:image])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:add_line1])
      devise_parameter_sanitizer.permit(:account_update, keys: [:add_line1])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:add_line2])
      devise_parameter_sanitizer.permit(:account_update, keys: [:add_line2])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:country])
      devise_parameter_sanitizer.permit(:account_update, keys: [:country])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:state])
      devise_parameter_sanitizer.permit(:account_update, keys: [:state])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:city])
      devise_parameter_sanitizer.permit(:account_update, keys: [:city])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:pin_code])
      devise_parameter_sanitizer.permit(:account_update, keys: [:pin_code])
    end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:create, :new]
  def show
    @user = current_user
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to edit_user_path(@user)
    else
      render :new
    end
  end
  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="user_nav">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. 
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      
    <% else %>
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.first_name %></h1>

<div>
      <%= image_tag @user.image_url.to_s %>  
      <div class="name"><%= @user.first_name %></div>
</div>

<%= link_to "Attempt exam" , user_exams_path(current_user.id) %>   <br>
<%= link_to "Attempt MCQ'S" , user_mcqs_path(current_user.id) %>   <br>
<%= link_to "Read E-Books" , user_ebooks_path(current_user.id) %>   <br>
<%= link_to "Watch Videos" , user_videos_path(current_user.id) %>  